server:
  port: 8083

spring:
  application:
    name: company-service
  # Postgresql database connection.
  datasource:
    url: jdbc:postgresql://localhost:5432/companyms
    username: user
    password: user
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect

# Eureka service registry.
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  # gateway - work with service-id in eureka
  instance:
    hostname: localhost


# zipkin distributed tracing.
management:
  tracing:
    sampling:
      probability: 1.0

# set details to "/info" actuator.
info:
  app:
    name: company-microservice
    description: This is a microservice named 'companyms' for JobWep-application build by Sajeevan.V
    version: 1.0.0